# Default values for devnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  init:
    limits:
      cpu: "1"
      memory: "1G"
    requests:
      cpu: "0.5"
      memory: "500M"
  wait:
    limits:
      cpu: "0.5"
      memory: "500M"
    requests:
      cpu: "0.2"
      memory: "200M"

exposer:
  image: anmol1696/exposer:20230319-e41e51f
  ports:
    rest: 8081
  resources:
    limits:
      cpu: "0.5"
      memory: "500M"
    requests:
      cpu: "0.2"
      memory: "200M"

# Chain timeouts
timeouts:
  time_iota_ms: 10
  timeout_propose: 3s
  timeout_propose_delta: 500ms
  timeout_prevote: 1s
  timeout_prevote_delta: 500ms
  timeout_precommit: 1s
  timeout_precommit_delta: 500ms
  timeout_commit: 5s

# API for interacting with the charts for devnet
# TODO: need a way to create state reaching jobs, those will run user bash scripts
# after the chain has been initialized, get the chain to a state and then complete
defaultChains:
  osmosis:
    image: anmol1696/osmosis:latest
    home: /root/.osmosisd
    binary: osmosisd
    prefix: osmo
    denom: uosmo
    coins: 100000000000000uosmo,100000000000000uion
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/osmosis-labs/osmosis
  juno:
    image: anmol1696/juno:latest
    home: /root/.juno
    binary: junod
    prefix: juno
    denom: ujuno
    coins: 100000000000000ujuno
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/CosmosContracts/juno
  wasmd:
    image: anmol1696/wasmd:latest
    home: /root/.wasmd
    binary: wasmd
    prefix: wasm
    denom: stake
    coins: 100000000000000ucosm,100000000000000stake
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/CosmWasm/wasmd
  cosmos:
    image: anmol1696/gaiad:latest
    home: /root/.gaia
    binary: gaiad
    prefix: cosmos
    denom: uatom
    coins: 100000000000000stake,100000000000000uatom
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmos/gaia
  persistencecore:
    image: anmol1696/persistencecore:latest
    home: /root/.persistenceCore
    binary: persistenceCore
    prefix: persistence
    denom: uxprt
    coins: 100000000000000uxprt
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/persistenceOne/persistenceCore
  xnet:
    image: ghcr.io/nextnet-works/xnet:0.1.0
    home: /root/.xnet
    binary: xnetd
    prefix: xnet
    denom: uxnet
    coins: 100000000000000uxnet
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/nextnet-works/xnet-chain.git

chains:
  - name: xnet-03012023
    type: xnet
    numValidators: 3
    upgrade:
      enabled: false
    ports:
      rpc: 26657
      rest: 1317
  # - name: core-1
  #   type: persistencecore
  #   numValidators: 3
  #   upgrade:
  #     enabled: true
  #     type: build
  #     genesis: v3.2.0
  #     upgrades:
  #       - name: v4
  #         version: v4.0.0
  #   ports:
  #     rpc: 26657
  #     rest: 1317
  # - name: juno-1
  #   type: juno
  #   numValidators: 2
  #   ports:
  #     rpc: 26654
  #     rest: 1314
  # - name: wasmd
  #   type: wasmd
  #   numValidators: 3
  #   ports:
  #     rpc: 26659
  #     rest: 1319

# TODO: ability to check the srcConnection and destConnection to use

explorer:
  # Flag to enable explorer for cluster
  enabled: true
  type: ping-pub
  image: ghcr.io/nextnet-works/explorer:1.0
  localhost: false
  ports:
    rest: 5173
  resources:
    limits:
      cpu: "0.5"
      memory: 2Gi
    requests:
      cpu: "0.25"
      memory: 1Gi


faucet:
  enabled: false

registry:
  enabled: false
  image: anmol1696/registry
  ports:
    rest: 6060
    grpc: 7070
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "0.5"
      memory: 1Gi

collector:
  enabled: false
  image: anmol1696/collector:latest
  localhost: true
  ports:
    rest: 8070
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "0.5"
      memory: 1Gi

