{{ $portMap := dict "p2p" 26656 "rpc" 26657 "grpc" 9090 "rest" 1317 }}
{{- range $chain := .Values.chains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chain.name }}-genesis
  labels:
    app.kubernetes.io/name: {{ $chain.name }}-genesis
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := $portMap }}
    - name: {{ $name }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
    {{- end }}
    - name: http
      port: {{ $.Values.exposer.port | default 8081 }}
      protocol: TCP
      targetPort: {{ $.Values.exposer.port | default 8081 }}
  selector:
    app.kubernetes.io/name: {{ $chain.name }}-genesis
---
{{- end }}
