{{- if .Values.explorer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app.kubernetes.io/name: explorer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5173
      protocol: TCP
      targetPort: 5173
  selector:
    app.kubernetes.io/name: explorer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: explorer
      app.kubernetes.io/name: explorer
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: explorer
        app.kubernetes.io/type: {{ .Values.explorer.type }}
        app.kubernetes.io/name: explorer
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      containers:
        - name: explorer
          args: ["--host", "0.0.0.0"]
          image: {{ .Values.explorer.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 2Gi
          volumeMounts:
            - mountPath: /home/explorer/src/chains/mainnet
              name: explorer-configs
          readinessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: explorer-configs
          configMap:
            name: explorer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer
data:
  {{- range $chain := .Values.chains }}
  {{ $defaultChain := get $.Values.defaultChains $chain.type }}
  {{ $host := "localhost" }}
  {{- if not $.Values.explorer.localhost }}
  {{ $host := printf "%s-genesis.%s.svc.cluster.local" $chain.name $.Release.Namespace }}
  {{- end }}
  {{ $chain.name }}.json: |-
    {
      "chain_name": "{{ $chain.name }}",
      "coingecko": "{{ $chain.type }}",
      "api": "http://{{ $chain.name }}-genesis.{{ $.Release.Namespace }}.svc.cluster.local:{{ $chain.ports.rest }}",
      "rpc": [
        "http://{{ $chain.name }}-genesis.{{ $.Release.Namespace }}.svc.cluster.local:{{ $chain.ports.rpc }}",
        "http://{{ $chain.name }}-genesis.{{ $.Release.Namespace }}.svc.cluster.local:{{ $chain.ports.rpc }}"
      ],
      "snapshot_provider": "",
      "sdk_version": "0.45.6",
      "coin_type": "{{ $defaultChain.coinType }}",
      "min_tx_fee": "3000",
      "addr_prefix": "{{ $defaultChain.prefix }}",
      "logo": "",
      "assets": [
        {
          "base": "{{ $defaultChain.denom }}",
          "symbol": "{{ $defaultChain.prefix | upper }}",
          "exponent": "6",
          "coingecko_id": "{{ $chain.name }}",
          "logo": ""
        }
      ]
    }
  {{- end }}
---
{{- end }}
